### PR TITLE
Integrating continuous benchmarking from js-logger

### PR DESCRIPTION
**Pull request by CMCDragonkai**
### Description

This brings in some synchronisation with js-logger and continuous benchmarking

### Issues Fixed

* Related https://github.com/MatrixAI/TypeScript-Demo-Lib/issues/54

### Tasks

- [x] 1. Updated continuous benchmarking framework
- [x] 2. Updated testing dependencies
- [x] 3. Updated `.gitlab-ci.yaml` to run benchmarks
- [x] 4. Changed to using `nix-shell --arg ci true --run $''` to ensure strict error checking AND also allow C-style string escaping
- [x] 5. Upgraded `ts-node` to using `swc`

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Here are the differences from the previous benchmark. This is run with `fixed-cpu-run npm run bench`.

```
[43375, 24504, 27503, 13785],

db_1KiB_ops{name="get 1 KiB of data"} 48563
db_1KiB_ops{name="put 1 KiB of data"} 39043
db_1KiB_ops{name="put zero data"} 40984
db_1KiB_ops{name="put zero data then del"} 21108

[570, 543, 29963, 13694],

db_1MiB_ops{name="get 1 MiB of data"} 821
db_1MiB_ops{name="put 1 MiB of data"} 638
db_1MiB_ops{name="put zero data"} 41831
db_1MiB_ops{name="put zero data then del"} 20022
```

**Comment by CMCDragonkai** [comment]
@tegefaulkes see benchmark data above.

**Comment by CMCDragonkai** [comment]
Error indicates that `js-logger` needs to be updated on `js-workers` first. Otherwise the strict type checking is failing. @emmacasolin

**Comment by emmacasolin** [comment]
> Error indicates that `js-logger` needs to be updated on `js-workers` first. Otherwise the strict type checking is failing. @emmacasolin

Just updated `js-workers` since `js-polykey` needs efs to be updated and efs needs `js-workers`, but it's not letting me push up the version tag for v1.3.4 of `js-workers`
```
remote: error: GH006: Protected tag update failed for refs/tags/v1.3.4.
remote: error: You're not authorized to create a tag
To github.com:MatrixAI/js-workers.git
 ! [remote rejected] v1.3.4 -> v1.3.4 (protected tag hook declined)
error: failed to push some refs to 'github.com:MatrixAI/js-workers.git'
```

**Comment by CMCDragonkai** [comment]
Permissions updated, you should be able to push protected tags to js-logger now.

**Comment by CMCDragonkai** [comment]
1.3.5 of js-workers is being staged.

**Comment by CMCDragonkai** [comment]
Going to merge now, and do the rest in `staging`.

**Pull request merged**
