### PR TITLE
Base128 encoding for keys

### LINKED ISSUE #27: Base Encoding for Keys
### Specification

Our usage of `0x00` null byte in our separators and escapes is causing ambiguity.

To resolve this, we can apply base encoding to our level parts and key part.

Base encoding would remove any possibility of `0x00` null byte in the output.

The simplest base encoding to apply would be base255, where we have 255 possible output symbols that does not include the `0x00` byte.

By doing this, null bytes don't appear in the stored level and key parts, and thus no ambiguity during parsing is possible. In fact parsing becomes simpler since we know that null bytes indicate the beginning and end of a part.

To understand how to do this, suppose we create a base algo called base128 (double of base64). And potentially evaluate the tradeoffs to base255.

The base encoding algorithms work like this. First we start with an alphabet.

In order to ensure lexicographic order, the alphabet must be in order. Base64 naturally does not have an ordered alphabet. But we can do this if we create our own encoding algorithm.

To create an 128-symbol alphabet:

```ts
const symbols: Array<number> = [];
// Start at 0x01 skipping 0x00
for (let i = 1; i < 129; i++) {
  symbols.push(i);
}
const alphabet = Buffer.from(symbols).toString('binary');
console.dir(alphabet);
```

Next we need to understand the encoding algorithm.

First we need to decide what the input bit-size group.

It is determined by `2**bitSize === numberOfSymbols`.

```
2**7 === 128
```

So for a base128, the bit size would be 7.

This means we take an arbitrary byte sequence as input, and split into groups of bitsize 7.

Any left-over partial group has to be left-padded with bit `0` until it reaches a a group of bitsize 7.

Then for each 7-group we map these to a symbol in our alphabet.

Here's a worked out example:

```ts
Input Byte -> Input Binary -> Input Split as Bit Group -> Output Mapped Decimal -> Output Hex
0x00 -> 0000 0000 -> 0000000 0000000 -> 1 1 -> 0x01 0x01
0x01 -> 0000 0001 -> 0000000 0000001 -> 1 2 -> 0x01 0x02
0x02 -> 0000 0010 -> 0000001 0000000 -> 2 1 -> 0x02 0x01
0x03 -> 0000 0011 -> 0000001 0000001 -> 2 2 -> 0x02 0x02
0x04 -> 0000 0100 -> 0000010 0000000 -> 3 1 -> 0x03 0x01
0x05 -> 0000 0101 -> 0000010 0000001 -> 3 2 -> 0x03 0x02
0x06 -> 0000 0110 -> 0000011 0000000 -> 4 1 -> 0x04 0x01
0x07 -> 0000 0111 -> 0000011 0000001 -> 4 2 -> 0x04 0x02
0x08 -> 0000 1000 -> 0000100 0000000 -> 5 1 -> 0x05 0x01
...
0xfe -> 1111 1110 -> 1111111 0000000 -> 128 1 -> 0x80 0x01
0xff -> 1111 1111 -> 1111111 0000001 -> 128 2 -> 0x80 0x02

What about 2 byte inputs?

0x00 0x00 -> 0000 0000 0000 0000 -> 0000000 0000000 0000000 -> 1 1 1   -> 0x01 0x01 0x01
0x00 0x01 -> 0000 0000 0000 0001 -> 0000000 0000000 0000001 -> 1 1 2   -> 0x01 0x01 0x02
...
0xfe 0x00 -> 1111 1110 0000 0000 -> 1111111 0000000 0000000 -> 128 1 1 -> 0x80 0x01 0x01
0xff 0x00 -> 1111 1111 0000 0000 -> 1111111 1000000 0000000 -> 128 65 1 -> 0x80 0x41 0x00
```

Notice that the input bytes are always at an 8-bit boundary. Meaning 1 byte is 8 bits, 2 bytes is 16 bits. Those bits are split into 7-bitsize groups. So for example `0x01` is `00000001`. That is split into `0000000` as the first group, and `1` as the second group. Because the second group is less than `7` bits in length, then it is left padded to `0000001`. These 2 groups are now mapped into the alphabet. The alphabet starts at `0x01`. Thus we get `0x01 0x02`.

You can work it out yourself and compare with the above mappings that I've worked out.

Notice that the resulting bytes would be in lexicographic order.

Now consider if there are 2 input bytes. The same idea applies.

Now there's a pattern to this. The output length of bytes is:

```
outputByteLength = Math.ceil((inputByteLength * 8) / bitSize)
```

With base128 we get about `~15%` extra bytes. Which is pretty good compared to base64 which increases the bytelength by 33%.

The algorithm for doing the bit-wise operations would be the same as how base64 does it. So just look for a javascript implementation of base64 and change the constants. There would be optimal ways of doing this very quickly.

Now what about base255? Suppose if we increase the size of the alphabet, surely we get more efficient algorithms that produce less overhead. Indeed there should be, but anything more than base128 should end up producing 2 character outputs for each 1 input character, unless we do it quite smart. I haven't worked it out fully, but the same idea should apply if we would use 15 bitsize groups to map into 2 byte outputs. However the algo I suspect may not as efficient. Not sure.

### Additional context

1. https://github.com/zanaptak/BinaryToTextEncoding
2. https://stackoverflow.com/a/23170407/582917

### Tasks

1. Look for a opensource base64 algo (preferably written in JS)
3. The nodejs source code is good, buffer encoding already supports base64, so you can just look there, or https://github.com/beatgammit/base64-js/blob/master/index.js
4. Reimplement it but swap the alphabet with the one created above and change the bitsize group from 6 to 7. Base64 normally uses bitsize group of 6 (as `2^6 === 64)
5. Then fuzz test with random keys to prove that lexi sort should work, remember `aa` is "greater" than `z`. So length matters too.

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description

We need to allow all possible characters to exist in our keys in order to allow random IDs to be used as keys. This has been causing issues with parsing our key paths since the separator character (`0x00`) could appear in the middle of a key. The solution is to base encode our keys to guarantee that the separator will not be present in the encoded version that goes into the DB. For now, we will stick with base 128 encoding since it is more efficient than base 64 and since we can allow non-printable characters. We may eventually upgrade to using base 255 for additional efficiency in the future.

### Issues Fixed

* Fixes #27 

### Tasks

- [x] 1. Create encoding/decoding utilities
- [x] 2. Update `parseKey` and `keyPathToKey` utilities to do encoding/decoding of path parts
- [x] 3. Update tests and add tests for encoding/decoding
- [x] 4. Remove the escape byte and any escaping functionality as it will not be used

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
I've added two utilities to `src/utils`:

```ts
// Create alphabet for encoding/decoding
const symbols: Array<number> = [];
// Start at 0x01 skipping 0x00
for (let i = 1; i < 129; i++) {
  symbols.push(i);
}
/**
 * Alphabet used for base encoding keys
 */
const alphabet = Buffer.from(symbols).toString('binary');

/**
 * Encode level or key part using base 128 encoding
 */
function encodePart(data: Buffer): string {
  // Start encoding
  const mask = (1 << 7) - 1
  let out = ''
  let bits = 0 // Number of bits currently in the buffer
  let buffer = 0 // Bits waiting to be written out, MSB first
  for (let i = 0; i < data.length; ++i) {
    // Slurp data into the buffer:
    buffer = (buffer << 8) | data[i]
    bits += 8
    // Write out as much as we can:
    while (bits > 7) {
      bits -= 7
      out += alphabet[mask & (buffer >> bits)]
    }
  }
  // Partial character:
  if (bits) {
    out += alphabet[mask & (buffer << (7 - bits))]
  }
  return out
}

/**
 * Decode level or string part from base 128 encoded string
 */
function decodePart(data: string): Buffer {
  const codes: Record<string, number> = {}
  for (let i = 0; i < alphabet.length; ++i) {
    codes[alphabet[i]] = i
  }
  // Count the padding bytes:
  let end = data.length
  while (data[end - 1] === '=') {
    --end
  }
  // Allocate the output:
  const out = new Uint8Array((end * 7 / 8) | 0)
  // Parse the data:
  let bits = 0 // Number of bits currently in the buffer
  let buffer = 0 // Bits waiting to be written out, MSB first
  let written = 0 // Next byte to write
  for (let i = 0; i < end; ++i) {
    // Read one character from the string:
    const value = codes[data[i]]
    if (value === undefined) {
      throw new SyntaxError(`Non-Base128 character`)
    }
    // Append the bits to the buffer:
    buffer = (buffer << 7) | value
    bits += 7
    // Write out some bits if the buffer has a byte's worth:
    if (bits >= 8) {
      bits -= 8
      out[written++] = 0xff & (buffer >> bits)
    }
  }
  return Buffer.from(out)
}
```

They were essentially copied straight from https://github.com/multiformats/js-multiformats/blob/master/src/bases/base.js but hard coded to work with base 128 rather than having the flexibility present in the original code. I also removed padding from the encoding function since we have no need for this https://github.com/MatrixAI/js-db/issues/27#issuecomment-1140442525.

The utilities appear to be working (able to encode and decode, decoded is the same as original), but I still need to test for lexicographic order once encoded.

**Comment by CMCDragonkai** [comment]
Great! As for testing lexicographic order, we currently have 4 tests in `DB.test.ts`:

* `lexicographic iteration order`
* `lexicographic buffer iteration order`
* `lexicographic integer iteration`
* `sublevel lexicographic iteration`

We should update these 2 tests with at least 100 random byte sequences.

* `lexicographic buffer iteration order`
* `sublevel lexicographic iteration`

Use `crypto.randomBytes` and give them random number of bytes. Like `crypto.randomBytes(Math.ceil(Math.random() * 100))`.

Generate a sequence of 100 of them. Then stick them into the DB as keys.

Then do an iteration, and you should expect the iteration order to be the same order as if you had sorted the original input buffers.

The tests already do this, but are limited in their samples that they are testing over.

As for the sublevel tests, it just needs to be done but this time with random sequences for each level, and random number of levels.

**Comment by CMCDragonkai** [comment]
Also this is a more efficient way of generating the alphabet:

```
const alphabet = Buffer.from(
  Array.from({ length: 128 }, (_, i) => {
    return i + 1;
  })
);
```

Note that I've left it as a buffer.

You should change your `encodePart` and `decodePart` to return it as a `Buffer`. That way we don't need to go buffer to string and back again.

**Comment by emmacasolin** [comment]
Do we want `db.dumb` to decode the keys? Considering it's mainly used for debugging it might be helpful to be able to see interpretable data, however it means that it's no longer dumping exactly what's in the db so that could add additional complexity/confusion as well. Maybe there should be an optional parameter for if you want the dump to be encoded or decoded?

**Comment by CMCDragonkai** [comment]
The `dump` should be decoding the keys. The usage of `raw `here indicates whether we return as `Buffer` for both keys and values.

The dumped return type is currently:

```
Promise<Array<[string | Buffer, any>>
```

So if we really want to do be precise we would want to do something like:

```
Promise<Array<[KeyPath, any]>>
```

Where `raw` controls the `any` to be `Buffer` or some decoded value from JSON, or `KeyPath` can be `[string | Buffer]`. I suppose `raw` true would give you `Buffer`, while `raw` false would give you `string`.

**Comment by CMCDragonkai** [comment]
We can release this as 4.0.2 once it is ready. External API hasn't changed, and it's a bug fix.

**Comment by emmacasolin** [comment]
Setting the `keyAsBuffer` option to false for the iterator doesn't seem to make a difference to the expected output. So for example this throws a type error since the compiler doesn't know if `kP` is an array of strings or buffers.
```ts
const keysIterated: Array<string> = [];
for await (const [kP] of db.iterator({ keyAsBuffer: false, values: false })) {
  keysIterated.push(kP[0]); // error here
}
```

**Comment by CMCDragonkai** [comment]
> Setting the `keyAsBuffer` option to false for the iterator doesn't seem to make a difference to the expected output. So for example this throws a type error since the compiler doesn't know if `kP` is an array of strings or buffers.
> 
> ```ts
> const keysIterated: Array<string> = [];
> for await (const [kP] of db.iterator({ keyAsBuffer: false, values: false })) {
>   keysIterated.push(kP[0]); // error here
> }
> ```

That's expected. Use an assertion `as string`.

**Comment by CMCDragonkai** [comment]
Big integer was only for sanity checking? So it can be ignored now as long as we know that leveldb iteration order matches `Buffer.compare` order.

**Comment by emmacasolin** [comment]
> We should update these 2 tests with at least 100 random byte sequences.
> 
> * `lexicographic buffer iteration order`
> * `sublevel lexicographic iteration`
> 
> Use `nodeCrypto.randomBytes` and give them random number of bytes. Like `nodeCrypto.randomBytes(Math.ceil(Math.random() * 100))`.
> 
> Generate a sequence of 100 of them. Then stick them into the DB as keys.
> 
> Then do an iteration, and you should expect the iteration order to be the same order as if you had sorted the original input buffers.
> 
> The tests already do this, but are limited in their samples that they are testing over.
> 
> As for the sublevel tests, it just needs to be done but this time with random sequences for each level, and random number of levels.

Rather than modifying the `sublevel lexicographic iteration` test I've added a new test called `sublevel lexicographic buffer iteration` (since that test is testing iteration over a sublevel rather than over all levels). For the new test, I'm generating 100 random arrays of buffers, with each array having a random length of between 0-10 levels, and each level having a random length of 0-10 bytes (so this way the total level paths are between 0-100 bytes).

In order to turn these paths into keys (so that they can be compared for lexicographic order) I'm not using the `keyPathToKey` utility, since that encodes the key/level parts. Instead, I'm reimplementing that logic in the test and just omitting the encoding.

With that, this PR just needs to be squashed and rebased and it should be ready to merge into staging.

**Comment by CMCDragonkai** [comment]
> In order to turn these paths into keys (so that they can be compared for lexicographic order) I'm not using the `keyPathToKey` utility, since that encodes the key/level parts. Instead, I'm reimplementing that logic in the test and just omitting the encoding.

In reimplementing the logic, do you mean you're just taking each buffer part of the keypath and concatenating them together into a buffer without the null bytes and without the encoding? That's one way to do it.

Then when testing iteration order, you only need to iterate from the root data level, and see that the keys being iterated matches the expected order of all the input buffers.

**Comment by emmacasolin** [comment]
> > In order to turn these paths into keys (so that they can be compared for lexicographic order) I'm not using the `keyPathToKey` utility, since that encodes the key/level parts. Instead, I'm reimplementing that logic in the test and just omitting the encoding.
> 
> In reimplementing the logic, do you mean you're just taking each buffer part of the keypath and concatenating them together into a buffer without the null byte separators and without the encoding? That's one way to do it.
> 
> Then when testing iteration order, you only need to iterate from the root data level, and see that the keys being iterated matches the expected order of all the input buffers.

I'm adding the separators but not the encoding. This is all after the keys have gone into the db and been iterated over. The key paths are put into the db as key paths and the concatenation and separators are added to both the original and returned iterated key paths before sorting the original ones and comparing the order. The sepatators are needed because they affect the lexicographic order and the iterated keys are in that order.

**Pull request merged**
